package top.sillyfan.auxiliaryplatform.domain.model;

import org.joda.time.DateTime;

public class AccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_token.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_token.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_token.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_token.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_token.expire
     *
     * @mbggenerated
     */
    private DateTime expire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_token.token
     *
     * @return the value of t_access_token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_token.token
     *
     * @param token the value for t_access_token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_token.username
     *
     * @return the value of t_access_token.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_token.username
     *
     * @param username the value for t_access_token.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_token.user_id
     *
     * @return the value of t_access_token.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_token.user_id
     *
     * @param userId the value for t_access_token.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_token.type
     *
     * @return the value of t_access_token.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_token.type
     *
     * @param type the value for t_access_token.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_token.expire
     *
     * @return the value of t_access_token.expire
     *
     * @mbggenerated
     */
    public DateTime getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_token.expire
     *
     * @param expire the value for t_access_token.expire
     *
     * @mbggenerated
     */
    public void setExpire(DateTime expire) {
        this.expire = expire;
    }
}