package top.sillyfan.auxiliaryplatform.domain.model;

import java.math.BigDecimal;
import org.joda.time.DateTime;
import top.sillyfan.auxiliaryplatform.domain.model.extend.RechargeRecordMore;

public class RechargeRecord extends RechargeRecordMore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_record.operator
     *
     * @mbggenerated
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_record.demander_id
     *
     * @mbggenerated
     */
    private Long demanderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_record.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_record.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge_record.create_time
     *
     * @mbggenerated
     */
    private DateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_record.id
     *
     * @return the value of t_recharge_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_record.id
     *
     * @param id the value for t_recharge_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_record.operator
     *
     * @return the value of t_recharge_record.operator
     *
     * @mbggenerated
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_record.operator
     *
     * @param operator the value for t_recharge_record.operator
     *
     * @mbggenerated
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_record.demander_id
     *
     * @return the value of t_recharge_record.demander_id
     *
     * @mbggenerated
     */
    public Long getDemanderId() {
        return demanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_record.demander_id
     *
     * @param demanderId the value for t_recharge_record.demander_id
     *
     * @mbggenerated
     */
    public void setDemanderId(Long demanderId) {
        this.demanderId = demanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_record.money
     *
     * @return the value of t_recharge_record.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_record.money
     *
     * @param money the value for t_recharge_record.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_record.type
     *
     * @return the value of t_recharge_record.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_record.type
     *
     * @param type the value for t_recharge_record.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge_record.create_time
     *
     * @return the value of t_recharge_record.create_time
     *
     * @mbggenerated
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge_record.create_time
     *
     * @param createTime the value for t_recharge_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }
}