package top.sillyfan.auxiliaryplatform.domain.model;

import org.joda.time.DateTime;
import top.sillyfan.auxiliaryplatform.domain.model.extend.SettlementMore;

public class Settlement extends SettlementMore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.auxiliary_id
     *
     * @mbggenerated
     */
    private Long auxiliaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.demander_id
     *
     * @mbggenerated
     */
    private Long demanderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.complete
     *
     * @mbggenerated
     */
    private Integer complete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.user_complete
     *
     * @mbggenerated
     */
    private Integer userComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_settlement.update_time
     *
     * @mbggenerated
     */
    private DateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.id
     *
     * @return the value of t_settlement.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.id
     *
     * @param id the value for t_settlement.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.auxiliary_id
     *
     * @return the value of t_settlement.auxiliary_id
     *
     * @mbggenerated
     */
    public Long getAuxiliaryId() {
        return auxiliaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.auxiliary_id
     *
     * @param auxiliaryId the value for t_settlement.auxiliary_id
     *
     * @mbggenerated
     */
    public void setAuxiliaryId(Long auxiliaryId) {
        this.auxiliaryId = auxiliaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.user_type
     *
     * @return the value of t_settlement.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.user_type
     *
     * @param userType the value for t_settlement.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.demander_id
     *
     * @return the value of t_settlement.demander_id
     *
     * @mbggenerated
     */
    public Long getDemanderId() {
        return demanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.demander_id
     *
     * @param demanderId the value for t_settlement.demander_id
     *
     * @mbggenerated
     */
    public void setDemanderId(Long demanderId) {
        this.demanderId = demanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.complete
     *
     * @return the value of t_settlement.complete
     *
     * @mbggenerated
     */
    public Integer getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.complete
     *
     * @param complete the value for t_settlement.complete
     *
     * @mbggenerated
     */
    public void setComplete(Integer complete) {
        this.complete = complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.user_complete
     *
     * @return the value of t_settlement.user_complete
     *
     * @mbggenerated
     */
    public Integer getUserComplete() {
        return userComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.user_complete
     *
     * @param userComplete the value for t_settlement.user_complete
     *
     * @mbggenerated
     */
    public void setUserComplete(Integer userComplete) {
        this.userComplete = userComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_settlement.update_time
     *
     * @return the value of t_settlement.update_time
     *
     * @mbggenerated
     */
    public DateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_settlement.update_time
     *
     * @param updateTime the value for t_settlement.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
    }
}