package top.sillyfan.auxiliaryplatform.domain.model;

import java.math.BigDecimal;
import org.joda.time.DateTime;
import top.sillyfan.auxiliaryplatform.domain.model.extend.TaskMore;

public class Task extends TaskMore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.qrcode
     *
     * @mbggenerated
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.demander_id
     *
     * @mbggenerated
     */
    private Long demanderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.auxiliary_id
     *
     * @mbggenerated
     */
    private Long auxiliaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.status_desc
     *
     * @mbggenerated
     */
    private String statusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.expire
     *
     * @mbggenerated
     */
    private Integer expire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.create_time
     *
     * @mbggenerated
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.update_time
     *
     * @mbggenerated
     */
    private DateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.old_id
     *
     * @mbggenerated
     */
    private String oldId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.id
     *
     * @return the value of t_task.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.id
     *
     * @param id the value for t_task.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.title
     *
     * @return the value of t_task.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.title
     *
     * @param title the value for t_task.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.qrcode
     *
     * @return the value of t_task.qrcode
     *
     * @mbggenerated
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.qrcode
     *
     * @param qrcode the value for t_task.qrcode
     *
     * @mbggenerated
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.content
     *
     * @return the value of t_task.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.content
     *
     * @param content the value for t_task.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.phone
     *
     * @return the value of t_task.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.phone
     *
     * @param phone the value for t_task.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.price
     *
     * @return the value of t_task.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.price
     *
     * @param price the value for t_task.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.demander_id
     *
     * @return the value of t_task.demander_id
     *
     * @mbggenerated
     */
    public Long getDemanderId() {
        return demanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.demander_id
     *
     * @param demanderId the value for t_task.demander_id
     *
     * @mbggenerated
     */
    public void setDemanderId(Long demanderId) {
        this.demanderId = demanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.auxiliary_id
     *
     * @return the value of t_task.auxiliary_id
     *
     * @mbggenerated
     */
    public Long getAuxiliaryId() {
        return auxiliaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.auxiliary_id
     *
     * @param auxiliaryId the value for t_task.auxiliary_id
     *
     * @mbggenerated
     */
    public void setAuxiliaryId(Long auxiliaryId) {
        this.auxiliaryId = auxiliaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.status
     *
     * @return the value of t_task.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.status
     *
     * @param status the value for t_task.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.status_desc
     *
     * @return the value of t_task.status_desc
     *
     * @mbggenerated
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.status_desc
     *
     * @param statusDesc the value for t_task.status_desc
     *
     * @mbggenerated
     */
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc == null ? null : statusDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.expire
     *
     * @return the value of t_task.expire
     *
     * @mbggenerated
     */
    public Integer getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.expire
     *
     * @param expire the value for t_task.expire
     *
     * @mbggenerated
     */
    public void setExpire(Integer expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.create_time
     *
     * @return the value of t_task.create_time
     *
     * @mbggenerated
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.create_time
     *
     * @param createTime the value for t_task.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.update_time
     *
     * @return the value of t_task.update_time
     *
     * @mbggenerated
     */
    public DateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.update_time
     *
     * @param updateTime the value for t_task.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.old_id
     *
     * @return the value of t_task.old_id
     *
     * @mbggenerated
     */
    public String getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.old_id
     *
     * @param oldId the value for t_task.old_id
     *
     * @mbggenerated
     */
    public void setOldId(String oldId) {
        this.oldId = oldId == null ? null : oldId.trim();
    }
}