package top.sillyfan.auxiliaryplatform.domain.model;

import top.sillyfan.auxiliaryplatform.domain.model.extend.UserConfigMore;
import top.sillyfan.auxiliaryplatform.domain.model.json.LongSet;

public class UserConfig extends UserConfigMore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.task_title
     *
     * @mbggenerated
     */
    private String taskTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.task_describe
     *
     * @mbggenerated
     */
    private String taskDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.task_expire
     *
     * @mbggenerated
     */
    private Integer taskExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.prefer_auxiliaries
     *
     * @mbggenerated
     */
    private LongSet preferAuxiliaries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_config.prefer_demanders
     *
     * @mbggenerated
     */
    private LongSet preferDemanders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.id
     *
     * @return the value of t_user_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.id
     *
     * @param id the value for t_user_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.user_id
     *
     * @return the value of t_user_config.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.user_id
     *
     * @param userId the value for t_user_config.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.task_title
     *
     * @return the value of t_user_config.task_title
     *
     * @mbggenerated
     */
    public String getTaskTitle() {
        return taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.task_title
     *
     * @param taskTitle the value for t_user_config.task_title
     *
     * @mbggenerated
     */
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle == null ? null : taskTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.task_describe
     *
     * @return the value of t_user_config.task_describe
     *
     * @mbggenerated
     */
    public String getTaskDescribe() {
        return taskDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.task_describe
     *
     * @param taskDescribe the value for t_user_config.task_describe
     *
     * @mbggenerated
     */
    public void setTaskDescribe(String taskDescribe) {
        this.taskDescribe = taskDescribe == null ? null : taskDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.task_expire
     *
     * @return the value of t_user_config.task_expire
     *
     * @mbggenerated
     */
    public Integer getTaskExpire() {
        return taskExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.task_expire
     *
     * @param taskExpire the value for t_user_config.task_expire
     *
     * @mbggenerated
     */
    public void setTaskExpire(Integer taskExpire) {
        this.taskExpire = taskExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.prefer_auxiliaries
     *
     * @return the value of t_user_config.prefer_auxiliaries
     *
     * @mbggenerated
     */
    public LongSet getPreferAuxiliaries() {
        return preferAuxiliaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.prefer_auxiliaries
     *
     * @param preferAuxiliaries the value for t_user_config.prefer_auxiliaries
     *
     * @mbggenerated
     */
    public void setPreferAuxiliaries(LongSet preferAuxiliaries) {
        this.preferAuxiliaries = preferAuxiliaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_config.prefer_demanders
     *
     * @return the value of t_user_config.prefer_demanders
     *
     * @mbggenerated
     */
    public LongSet getPreferDemanders() {
        return preferDemanders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_config.prefer_demanders
     *
     * @param preferDemanders the value for t_user_config.prefer_demanders
     *
     * @mbggenerated
     */
    public void setPreferDemanders(LongSet preferDemanders) {
        this.preferDemanders = preferDemanders;
    }
}