package top.sillyfan.auxiliaryplatform.domain.model;

import java.math.BigDecimal;
import org.joda.time.DateTime;
import top.sillyfan.auxiliaryplatform.domain.model.json.StringList;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.superUser
     *
     * @mbggenerated
     */
    private Long superuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.online
     *
     * @mbggenerated
     */
    private Integer online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.authorizes
     *
     * @mbggenerated
     */
    private StringList authorizes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.taskStatus
     *
     * @mbggenerated
     */
    private Integer taskstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lastPasswordResetDate
     *
     * @mbggenerated
     */
    private DateTime lastpasswordresetdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.superUser
     *
     * @return the value of t_user.superUser
     *
     * @mbggenerated
     */
    public Long getSuperuser() {
        return superuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.superUser
     *
     * @param superuser the value for t_user.superUser
     *
     * @mbggenerated
     */
    public void setSuperuser(Long superuser) {
        this.superuser = superuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.qq
     *
     * @return the value of t_user.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.qq
     *
     * @param qq the value for t_user.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.type
     *
     * @return the value of t_user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.type
     *
     * @param type the value for t_user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.online
     *
     * @return the value of t_user.online
     *
     * @mbggenerated
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.online
     *
     * @param online the value for t_user.online
     *
     * @mbggenerated
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.price
     *
     * @return the value of t_user.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.price
     *
     * @param price the value for t_user.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.balance
     *
     * @return the value of t_user.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.balance
     *
     * @param balance the value for t_user.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.authorizes
     *
     * @return the value of t_user.authorizes
     *
     * @mbggenerated
     */
    public StringList getAuthorizes() {
        return authorizes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.authorizes
     *
     * @param authorizes the value for t_user.authorizes
     *
     * @mbggenerated
     */
    public void setAuthorizes(StringList authorizes) {
        this.authorizes = authorizes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.taskStatus
     *
     * @return the value of t_user.taskStatus
     *
     * @mbggenerated
     */
    public Integer getTaskstatus() {
        return taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.taskStatus
     *
     * @param taskstatus the value for t_user.taskStatus
     *
     * @mbggenerated
     */
    public void setTaskstatus(Integer taskstatus) {
        this.taskstatus = taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lastPasswordResetDate
     *
     * @return the value of t_user.lastPasswordResetDate
     *
     * @mbggenerated
     */
    public DateTime getLastpasswordresetdate() {
        return lastpasswordresetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lastPasswordResetDate
     *
     * @param lastpasswordresetdate the value for t_user.lastPasswordResetDate
     *
     * @mbggenerated
     */
    public void setLastpasswordresetdate(DateTime lastpasswordresetdate) {
        this.lastpasswordresetdate = lastpasswordresetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mark
     *
     * @return the value of t_user.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mark
     *
     * @param mark the value for t_user.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}